/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Jul 27 18:50:57 2018. */

#ifndef PB_KRPC_SCHEMA_KRPC_PB_H_INCLUDED
#define PB_KRPC_SCHEMA_KRPC_PB_H_INCLUDED
#include <krpc/pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _krpc_schema_ConnectionRequest_Type {
    krpc_schema_ConnectionRequest_Type_RPC = 0,
    krpc_schema_ConnectionRequest_Type_STREAM = 1
} krpc_schema_ConnectionRequest_Type;
#define _krpc_schema_ConnectionRequest_Type_MIN krpc_schema_ConnectionRequest_Type_RPC
#define _krpc_schema_ConnectionRequest_Type_MAX krpc_schema_ConnectionRequest_Type_STREAM
#define _krpc_schema_ConnectionRequest_Type_ARRAYSIZE ((krpc_schema_ConnectionRequest_Type)(krpc_schema_ConnectionRequest_Type_STREAM+1))

typedef enum _krpc_schema_ConnectionResponse_Status {
    krpc_schema_ConnectionResponse_Status_OK = 0,
    krpc_schema_ConnectionResponse_Status_MALFORMED_MESSAGE = 1,
    krpc_schema_ConnectionResponse_Status_TIMEOUT = 2,
    krpc_schema_ConnectionResponse_Status_WRONG_TYPE = 3
} krpc_schema_ConnectionResponse_Status;
#define _krpc_schema_ConnectionResponse_Status_MIN krpc_schema_ConnectionResponse_Status_OK
#define _krpc_schema_ConnectionResponse_Status_MAX krpc_schema_ConnectionResponse_Status_WRONG_TYPE
#define _krpc_schema_ConnectionResponse_Status_ARRAYSIZE ((krpc_schema_ConnectionResponse_Status)(krpc_schema_ConnectionResponse_Status_WRONG_TYPE+1))

typedef enum _krpc_schema_Type_TypeCode {
    krpc_schema_Type_TypeCode_NONE = 0,
    krpc_schema_Type_TypeCode_DOUBLE = 1,
    krpc_schema_Type_TypeCode_FLOAT = 2,
    krpc_schema_Type_TypeCode_SINT32 = 3,
    krpc_schema_Type_TypeCode_SINT64 = 4,
    krpc_schema_Type_TypeCode_UINT32 = 5,
    krpc_schema_Type_TypeCode_UINT64 = 6,
    krpc_schema_Type_TypeCode_BOOL = 7,
    krpc_schema_Type_TypeCode_STRING = 8,
    krpc_schema_Type_TypeCode_BYTES = 9,
    krpc_schema_Type_TypeCode_CLASS = 100,
    krpc_schema_Type_TypeCode_ENUMERATION = 101,
    krpc_schema_Type_TypeCode_EVENT = 200,
    krpc_schema_Type_TypeCode_PROCEDURE_CALL = 201,
    krpc_schema_Type_TypeCode_STREAM = 202,
    krpc_schema_Type_TypeCode_STATUS = 203,
    krpc_schema_Type_TypeCode_SERVICES = 204,
    krpc_schema_Type_TypeCode_TUPLE = 300,
    krpc_schema_Type_TypeCode_LIST = 301,
    krpc_schema_Type_TypeCode_SET = 302,
    krpc_schema_Type_TypeCode_DICTIONARY = 303
} krpc_schema_Type_TypeCode;
#define _krpc_schema_Type_TypeCode_MIN krpc_schema_Type_TypeCode_NONE
#define _krpc_schema_Type_TypeCode_MAX krpc_schema_Type_TypeCode_DICTIONARY
#define _krpc_schema_Type_TypeCode_ARRAYSIZE ((krpc_schema_Type_TypeCode)(krpc_schema_Type_TypeCode_DICTIONARY+1))

/* Struct definitions */
typedef struct _krpc_schema_Class {
    pb_callback_t name;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_Class) */
} krpc_schema_Class;

typedef struct _krpc_schema_Dictionary {
    pb_callback_t entries;
/* @@protoc_insertion_point(struct:krpc_schema_Dictionary) */
} krpc_schema_Dictionary;

typedef struct _krpc_schema_DictionaryEntry {
    pb_callback_t key;
    pb_callback_t value;
/* @@protoc_insertion_point(struct:krpc_schema_DictionaryEntry) */
} krpc_schema_DictionaryEntry;

typedef struct _krpc_schema_Enumeration {
    pb_callback_t name;
    pb_callback_t values;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_Enumeration) */
} krpc_schema_Enumeration;

typedef struct _krpc_schema_Error {
    pb_callback_t service;
    pb_callback_t name;
    pb_callback_t description;
    pb_callback_t stack_trace;
/* @@protoc_insertion_point(struct:krpc_schema_Error) */
} krpc_schema_Error;

typedef struct _krpc_schema_Exception {
    pb_callback_t name;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_Exception) */
} krpc_schema_Exception;

typedef struct _krpc_schema_List {
    pb_callback_t items;
/* @@protoc_insertion_point(struct:krpc_schema_List) */
} krpc_schema_List;

typedef struct _krpc_schema_ProcedureResult {
    pb_callback_t error;
    pb_callback_t value;
/* @@protoc_insertion_point(struct:krpc_schema_ProcedureResult) */
} krpc_schema_ProcedureResult;

typedef struct _krpc_schema_Service {
    pb_callback_t name;
    pb_callback_t procedures;
    pb_callback_t classes;
    pb_callback_t enumerations;
    pb_callback_t exceptions;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_Service) */
} krpc_schema_Service;

typedef struct _krpc_schema_Services {
    pb_callback_t services;
/* @@protoc_insertion_point(struct:krpc_schema_Services) */
} krpc_schema_Services;

typedef struct _krpc_schema_Set {
    pb_callback_t items;
/* @@protoc_insertion_point(struct:krpc_schema_Set) */
} krpc_schema_Set;

typedef struct _krpc_schema_StreamUpdate {
    pb_callback_t results;
/* @@protoc_insertion_point(struct:krpc_schema_StreamUpdate) */
} krpc_schema_StreamUpdate;

typedef struct _krpc_schema_Tuple {
    pb_callback_t items;
/* @@protoc_insertion_point(struct:krpc_schema_Tuple) */
} krpc_schema_Tuple;

typedef struct _krpc_schema_Argument {
    uint32_t position;
    pb_callback_t value;
/* @@protoc_insertion_point(struct:krpc_schema_Argument) */
} krpc_schema_Argument;

typedef struct _krpc_schema_ConnectionRequest {
    krpc_schema_ConnectionRequest_Type type;
    pb_callback_t client_name;
    pb_callback_t client_identifier;
/* @@protoc_insertion_point(struct:krpc_schema_ConnectionRequest) */
} krpc_schema_ConnectionRequest;

typedef struct _krpc_schema_ConnectionResponse {
    krpc_schema_ConnectionResponse_Status status;
    pb_callback_t message;
    pb_callback_t client_identifier;
/* @@protoc_insertion_point(struct:krpc_schema_ConnectionResponse) */
} krpc_schema_ConnectionResponse;

typedef struct _krpc_schema_EnumerationValue {
    pb_callback_t name;
    int32_t value;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_EnumerationValue) */
} krpc_schema_EnumerationValue;

typedef struct _krpc_schema_ProcedureCall {
    char service[0];
    char procedure[0];
    pb_callback_t arguments;
    uint32_t service_id;
    uint32_t procedure_id;
/* @@protoc_insertion_point(struct:krpc_schema_ProcedureCall) */
} krpc_schema_ProcedureCall;

typedef struct _krpc_schema_Response {
    pb_callback_t error;
    pb_size_t results_count;
    krpc_schema_ProcedureResult results[1];
/* @@protoc_insertion_point(struct:krpc_schema_Response) */
} krpc_schema_Response;

typedef struct _krpc_schema_Status {
    char version[16];
    uint64_t bytes_read;
    uint64_t bytes_written;
    float bytes_read_rate;
    float bytes_written_rate;
    uint64_t rpcs_executed;
    float rpc_rate;
    bool one_rpc_per_update;
    uint32_t max_time_per_update;
    bool adaptive_rate_control;
    bool blocking_recv;
    uint32_t recv_timeout;
    float time_per_rpc_update;
    float poll_time_per_rpc_update;
    float exec_time_per_rpc_update;
    uint32_t stream_rpcs;
    uint64_t stream_rpcs_executed;
    float stream_rpc_rate;
    float time_per_stream_update;
/* @@protoc_insertion_point(struct:krpc_schema_Status) */
} krpc_schema_Status;

typedef struct _krpc_schema_Stream {
    uint64_t id;
/* @@protoc_insertion_point(struct:krpc_schema_Stream) */
} krpc_schema_Stream;

typedef struct _krpc_schema_StreamResult {
    uint64_t id;
    krpc_schema_ProcedureResult result;
/* @@protoc_insertion_point(struct:krpc_schema_StreamResult) */
} krpc_schema_StreamResult;

typedef struct _krpc_schema_Type {
    krpc_schema_Type_TypeCode code;
    pb_callback_t service;
    pb_callback_t name;
    pb_callback_t types;
/* @@protoc_insertion_point(struct:krpc_schema_Type) */
} krpc_schema_Type;

typedef struct _krpc_schema_Event {
    krpc_schema_Stream stream;
/* @@protoc_insertion_point(struct:krpc_schema_Event) */
} krpc_schema_Event;

typedef struct _krpc_schema_MultiplexedResponse {
    krpc_schema_Response response;
    krpc_schema_StreamUpdate stream_update;
/* @@protoc_insertion_point(struct:krpc_schema_MultiplexedResponse) */
} krpc_schema_MultiplexedResponse;

typedef struct _krpc_schema_Parameter {
    pb_callback_t name;
    krpc_schema_Type type;
    pb_callback_t default_value;
/* @@protoc_insertion_point(struct:krpc_schema_Parameter) */
} krpc_schema_Parameter;

typedef struct _krpc_schema_Procedure {
    pb_callback_t name;
    pb_callback_t parameters;
    krpc_schema_Type return_type;
    bool return_is_nullable;
    pb_callback_t documentation;
/* @@protoc_insertion_point(struct:krpc_schema_Procedure) */
} krpc_schema_Procedure;

typedef struct _krpc_schema_Request {
    pb_size_t calls_count;
    krpc_schema_ProcedureCall calls[1];
/* @@protoc_insertion_point(struct:krpc_schema_Request) */
} krpc_schema_Request;

typedef struct _krpc_schema_MultiplexedRequest {
    krpc_schema_ConnectionRequest connection_request;
    krpc_schema_Request request;
/* @@protoc_insertion_point(struct:krpc_schema_MultiplexedRequest) */
} krpc_schema_MultiplexedRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define krpc_schema_ConnectionRequest_init_default {(krpc_schema_ConnectionRequest_Type)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_ConnectionResponse_init_default {(krpc_schema_ConnectionResponse_Status)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Request_init_default         {0, {krpc_schema_ProcedureCall_init_default}}
#define krpc_schema_ProcedureCall_init_default   {"", "", {{NULL}, NULL}, 0, 0}
#define krpc_schema_Argument_init_default        {0, {{NULL}, NULL}}
#define krpc_schema_Response_init_default        {{{NULL}, NULL}, 0, {krpc_schema_ProcedureResult_init_default}}
#define krpc_schema_ProcedureResult_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Error_init_default           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_StreamUpdate_init_default    {{{NULL}, NULL}}
#define krpc_schema_StreamResult_init_default    {0, krpc_schema_ProcedureResult_init_default}
#define krpc_schema_Services_init_default        {{{NULL}, NULL}}
#define krpc_schema_Service_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Procedure_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, krpc_schema_Type_init_default, 0, {{NULL}, NULL}}
#define krpc_schema_Parameter_init_default       {{{NULL}, NULL}, krpc_schema_Type_init_default, {{NULL}, NULL}}
#define krpc_schema_Class_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Enumeration_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_EnumerationValue_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define krpc_schema_Exception_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Type_init_default            {(krpc_schema_Type_TypeCode)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Tuple_init_default           {{{NULL}, NULL}}
#define krpc_schema_List_init_default            {{{NULL}, NULL}}
#define krpc_schema_Set_init_default             {{{NULL}, NULL}}
#define krpc_schema_Dictionary_init_default      {{{NULL}, NULL}}
#define krpc_schema_DictionaryEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Stream_init_default          {0}
#define krpc_schema_Event_init_default           {krpc_schema_Stream_init_default}
#define krpc_schema_Status_init_default          {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define krpc_schema_MultiplexedRequest_init_default {krpc_schema_ConnectionRequest_init_default, krpc_schema_Request_init_default}
#define krpc_schema_MultiplexedResponse_init_default {krpc_schema_Response_init_default, krpc_schema_StreamUpdate_init_default}
#define krpc_schema_ConnectionRequest_init_zero  {(krpc_schema_ConnectionRequest_Type)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_ConnectionResponse_init_zero {(krpc_schema_ConnectionResponse_Status)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Request_init_zero            {0, {krpc_schema_ProcedureCall_init_zero}}
#define krpc_schema_ProcedureCall_init_zero      {"", "", {{NULL}, NULL}, 0, 0}
#define krpc_schema_Argument_init_zero           {0, {{NULL}, NULL}}
#define krpc_schema_Response_init_zero           {{{NULL}, NULL}, 0, {krpc_schema_ProcedureResult_init_zero}}
#define krpc_schema_ProcedureResult_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Error_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_StreamUpdate_init_zero       {{{NULL}, NULL}}
#define krpc_schema_StreamResult_init_zero       {0, krpc_schema_ProcedureResult_init_zero}
#define krpc_schema_Services_init_zero           {{{NULL}, NULL}}
#define krpc_schema_Service_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Procedure_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, krpc_schema_Type_init_zero, 0, {{NULL}, NULL}}
#define krpc_schema_Parameter_init_zero          {{{NULL}, NULL}, krpc_schema_Type_init_zero, {{NULL}, NULL}}
#define krpc_schema_Class_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Enumeration_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_EnumerationValue_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define krpc_schema_Exception_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Type_init_zero               {(krpc_schema_Type_TypeCode)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Tuple_init_zero              {{{NULL}, NULL}}
#define krpc_schema_List_init_zero               {{{NULL}, NULL}}
#define krpc_schema_Set_init_zero                {{{NULL}, NULL}}
#define krpc_schema_Dictionary_init_zero         {{{NULL}, NULL}}
#define krpc_schema_DictionaryEntry_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}}
#define krpc_schema_Stream_init_zero             {0}
#define krpc_schema_Event_init_zero              {krpc_schema_Stream_init_zero}
#define krpc_schema_Status_init_zero             {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define krpc_schema_MultiplexedRequest_init_zero {krpc_schema_ConnectionRequest_init_zero, krpc_schema_Request_init_zero}
#define krpc_schema_MultiplexedResponse_init_zero {krpc_schema_Response_init_zero, krpc_schema_StreamUpdate_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define krpc_schema_Class_name_tag               1
#define krpc_schema_Class_documentation_tag      2
#define krpc_schema_Dictionary_entries_tag       1
#define krpc_schema_DictionaryEntry_key_tag      1
#define krpc_schema_DictionaryEntry_value_tag    2
#define krpc_schema_Enumeration_name_tag         1
#define krpc_schema_Enumeration_values_tag       2
#define krpc_schema_Enumeration_documentation_tag 3
#define krpc_schema_Error_service_tag            1
#define krpc_schema_Error_name_tag               2
#define krpc_schema_Error_description_tag        3
#define krpc_schema_Error_stack_trace_tag        4
#define krpc_schema_Exception_name_tag           1
#define krpc_schema_Exception_documentation_tag  2
#define krpc_schema_List_items_tag               1
#define krpc_schema_ProcedureResult_error_tag    1
#define krpc_schema_ProcedureResult_value_tag    2
#define krpc_schema_Service_name_tag             1
#define krpc_schema_Service_procedures_tag       2
#define krpc_schema_Service_classes_tag          3
#define krpc_schema_Service_enumerations_tag     4
#define krpc_schema_Service_exceptions_tag       5
#define krpc_schema_Service_documentation_tag    6
#define krpc_schema_Services_services_tag        1
#define krpc_schema_Set_items_tag                1
#define krpc_schema_StreamUpdate_results_tag     1
#define krpc_schema_Tuple_items_tag              1
#define krpc_schema_Argument_position_tag        1
#define krpc_schema_Argument_value_tag           2
#define krpc_schema_ConnectionRequest_type_tag   1
#define krpc_schema_ConnectionRequest_client_name_tag 2
#define krpc_schema_ConnectionRequest_client_identifier_tag 3
#define krpc_schema_ConnectionResponse_status_tag 1
#define krpc_schema_ConnectionResponse_message_tag 2
#define krpc_schema_ConnectionResponse_client_identifier_tag 3
#define krpc_schema_EnumerationValue_name_tag    1
#define krpc_schema_EnumerationValue_value_tag   2
#define krpc_schema_EnumerationValue_documentation_tag 3
#define krpc_schema_ProcedureCall_service_tag    1
#define krpc_schema_ProcedureCall_procedure_tag  2
#define krpc_schema_ProcedureCall_service_id_tag 4
#define krpc_schema_ProcedureCall_procedure_id_tag 5
#define krpc_schema_ProcedureCall_arguments_tag  3
#define krpc_schema_Response_error_tag           1
#define krpc_schema_Response_results_tag         2
#define krpc_schema_Status_version_tag           1
#define krpc_schema_Status_bytes_read_tag        2
#define krpc_schema_Status_bytes_written_tag     3
#define krpc_schema_Status_bytes_read_rate_tag   4
#define krpc_schema_Status_bytes_written_rate_tag 5
#define krpc_schema_Status_rpcs_executed_tag     6
#define krpc_schema_Status_rpc_rate_tag          7
#define krpc_schema_Status_one_rpc_per_update_tag 8
#define krpc_schema_Status_max_time_per_update_tag 9
#define krpc_schema_Status_adaptive_rate_control_tag 10
#define krpc_schema_Status_blocking_recv_tag     11
#define krpc_schema_Status_recv_timeout_tag      12
#define krpc_schema_Status_time_per_rpc_update_tag 13
#define krpc_schema_Status_poll_time_per_rpc_update_tag 14
#define krpc_schema_Status_exec_time_per_rpc_update_tag 15
#define krpc_schema_Status_stream_rpcs_tag       16
#define krpc_schema_Status_stream_rpcs_executed_tag 17
#define krpc_schema_Status_stream_rpc_rate_tag   18
#define krpc_schema_Status_time_per_stream_update_tag 19
#define krpc_schema_Stream_id_tag                1
#define krpc_schema_StreamResult_id_tag          1
#define krpc_schema_StreamResult_result_tag      2
#define krpc_schema_Type_code_tag                1
#define krpc_schema_Type_service_tag             2
#define krpc_schema_Type_name_tag                3
#define krpc_schema_Type_types_tag               4
#define krpc_schema_Event_stream_tag             1
#define krpc_schema_MultiplexedResponse_response_tag 1
#define krpc_schema_MultiplexedResponse_stream_update_tag 2
#define krpc_schema_Parameter_name_tag           1
#define krpc_schema_Parameter_type_tag           2
#define krpc_schema_Parameter_default_value_tag  3
#define krpc_schema_Procedure_name_tag           1
#define krpc_schema_Procedure_parameters_tag     2
#define krpc_schema_Procedure_return_type_tag    3
#define krpc_schema_Procedure_return_is_nullable_tag 4
#define krpc_schema_Procedure_documentation_tag  5
#define krpc_schema_Request_calls_tag            1
#define krpc_schema_MultiplexedRequest_connection_request_tag 1
#define krpc_schema_MultiplexedRequest_request_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t krpc_schema_ConnectionRequest_fields[4];
extern const pb_field_t krpc_schema_ConnectionResponse_fields[4];
extern const pb_field_t krpc_schema_Request_fields[2];
extern const pb_field_t krpc_schema_ProcedureCall_fields[6];
extern const pb_field_t krpc_schema_Argument_fields[3];
extern const pb_field_t krpc_schema_Response_fields[3];
extern const pb_field_t krpc_schema_ProcedureResult_fields[3];
extern const pb_field_t krpc_schema_Error_fields[5];
extern const pb_field_t krpc_schema_StreamUpdate_fields[2];
extern const pb_field_t krpc_schema_StreamResult_fields[3];
extern const pb_field_t krpc_schema_Services_fields[2];
extern const pb_field_t krpc_schema_Service_fields[7];
extern const pb_field_t krpc_schema_Procedure_fields[6];
extern const pb_field_t krpc_schema_Parameter_fields[4];
extern const pb_field_t krpc_schema_Class_fields[3];
extern const pb_field_t krpc_schema_Enumeration_fields[4];
extern const pb_field_t krpc_schema_EnumerationValue_fields[4];
extern const pb_field_t krpc_schema_Exception_fields[3];
extern const pb_field_t krpc_schema_Type_fields[5];
extern const pb_field_t krpc_schema_Tuple_fields[2];
extern const pb_field_t krpc_schema_List_fields[2];
extern const pb_field_t krpc_schema_Set_fields[2];
extern const pb_field_t krpc_schema_Dictionary_fields[2];
extern const pb_field_t krpc_schema_DictionaryEntry_fields[3];
extern const pb_field_t krpc_schema_Stream_fields[2];
extern const pb_field_t krpc_schema_Event_fields[2];
extern const pb_field_t krpc_schema_Status_fields[20];
extern const pb_field_t krpc_schema_MultiplexedRequest_fields[3];
extern const pb_field_t krpc_schema_MultiplexedResponse_fields[3];

/* Maximum encoded size of messages (where known) */
/* krpc_schema_ConnectionRequest_size depends on runtime parameters */
/* krpc_schema_ConnectionResponse_size depends on runtime parameters */
#define krpc_schema_Request_size                 (6 + 1*krpc_schema_ProcedureCall_size)
/* krpc_schema_ProcedureCall_size depends on runtime parameters */
/* krpc_schema_Argument_size depends on runtime parameters */
/* krpc_schema_Response_size depends on runtime parameters */
/* krpc_schema_ProcedureResult_size depends on runtime parameters */
/* krpc_schema_Error_size depends on runtime parameters */
/* krpc_schema_StreamUpdate_size depends on runtime parameters */
#define krpc_schema_StreamResult_size            (17 + krpc_schema_ProcedureResult_size)
/* krpc_schema_Services_size depends on runtime parameters */
/* krpc_schema_Service_size depends on runtime parameters */
/* krpc_schema_Procedure_size depends on runtime parameters */
/* krpc_schema_Parameter_size depends on runtime parameters */
/* krpc_schema_Class_size depends on runtime parameters */
/* krpc_schema_Enumeration_size depends on runtime parameters */
/* krpc_schema_EnumerationValue_size depends on runtime parameters */
/* krpc_schema_Exception_size depends on runtime parameters */
/* krpc_schema_Type_size depends on runtime parameters */
/* krpc_schema_Tuple_size depends on runtime parameters */
/* krpc_schema_List_size depends on runtime parameters */
/* krpc_schema_Set_size depends on runtime parameters */
/* krpc_schema_Dictionary_size depends on runtime parameters */
/* krpc_schema_DictionaryEntry_size depends on runtime parameters */
#define krpc_schema_Stream_size                  11
#define krpc_schema_Event_size                   13
#define krpc_schema_Status_size                  130
#define krpc_schema_MultiplexedRequest_size      (18 + krpc_schema_ConnectionRequest_size + 1*krpc_schema_ProcedureCall_size)
#define krpc_schema_MultiplexedResponse_size     (12 + krpc_schema_Response_size + krpc_schema_StreamUpdate_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define KRPC_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
