/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "krpc/krpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(krpc_schema_ConnectionRequest, krpc_schema_ConnectionRequest, AUTO)


PB_BIND(krpc_schema_ConnectionResponse, krpc_schema_ConnectionResponse, AUTO)


PB_BIND(krpc_schema_Request, krpc_schema_Request, AUTO)


PB_BIND(krpc_schema_ProcedureCall, krpc_schema_ProcedureCall, AUTO)


PB_BIND(krpc_schema_Argument, krpc_schema_Argument, AUTO)


PB_BIND(krpc_schema_Response, krpc_schema_Response, AUTO)


PB_BIND(krpc_schema_ProcedureResult, krpc_schema_ProcedureResult, AUTO)


PB_BIND(krpc_schema_Error, krpc_schema_Error, AUTO)


PB_BIND(krpc_schema_StreamUpdate, krpc_schema_StreamUpdate, AUTO)


PB_BIND(krpc_schema_StreamResult, krpc_schema_StreamResult, AUTO)


PB_BIND(krpc_schema_Services, krpc_schema_Services, AUTO)


PB_BIND(krpc_schema_Service, krpc_schema_Service, AUTO)


PB_BIND(krpc_schema_Procedure, krpc_schema_Procedure, AUTO)


PB_BIND(krpc_schema_Parameter, krpc_schema_Parameter, AUTO)


PB_BIND(krpc_schema_Class, krpc_schema_Class, AUTO)


PB_BIND(krpc_schema_Enumeration, krpc_schema_Enumeration, AUTO)


PB_BIND(krpc_schema_EnumerationValue, krpc_schema_EnumerationValue, AUTO)


PB_BIND(krpc_schema_Exception, krpc_schema_Exception, AUTO)


PB_BIND(krpc_schema_Type, krpc_schema_Type, AUTO)


PB_BIND(krpc_schema_Tuple, krpc_schema_Tuple, AUTO)


PB_BIND(krpc_schema_List, krpc_schema_List, AUTO)


PB_BIND(krpc_schema_Set, krpc_schema_Set, AUTO)


PB_BIND(krpc_schema_Dictionary, krpc_schema_Dictionary, AUTO)


PB_BIND(krpc_schema_DictionaryEntry, krpc_schema_DictionaryEntry, AUTO)


PB_BIND(krpc_schema_Stream, krpc_schema_Stream, AUTO)


PB_BIND(krpc_schema_Event, krpc_schema_Event, AUTO)


PB_BIND(krpc_schema_Status, krpc_schema_Status, AUTO)


PB_BIND(krpc_schema_MultiplexedRequest, krpc_schema_MultiplexedRequest, AUTO)


PB_BIND(krpc_schema_MultiplexedResponse, krpc_schema_MultiplexedResponse, AUTO)







